services:
  db:
    image: ankane/pgvector:latest
    container_name: guepard-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ai_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
