"""Initial schema v23.5

Revision ID: b6bd37af0df9
Revises: 
Create Date: 2026-04-27 23:55:24.409172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6bd37af0df9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'brand_artistic_essence', 'brands', ['brand_id'], ['id'])
    op.alter_column('brand_assets', 'source_doc',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.drop_constraint(op.f('brand_visual_dna_brand_id_key'), 'brand_visual_dna', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('brand_visual_dna_brand_id_key'), 'brand_visual_dna', ['brand_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('brand_assets', 'source_doc',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.drop_constraint(None, 'brand_artistic_essence', type_='foreignkey')
    # ### end Alembic commands ###
